---
parser: '@typescript-eslint/parser'
parserOptions:
  project: tsconfig.json
  sourceType: module

plugins:
  - simple-import-sort
  - jsx-a11y

extends:
  - 'plugin:@typescript-eslint/recommended'
  - prettier
  - react-app
  - 'plugin:jsx-a11y/recommended'

env:
  node: true

globals:
  __DEV__: true

rules:
  '@typescript-eslint/no-empty-interface': 'off'
  '@typescript-eslint/interface-name-prefix': 'off'
  '@typescript-eslint/explicit-function-return-type': 'off'
  '@typescript-eslint/no-explicit-any': 'off'
  '@typescript-eslint/camelcase': 'off'
  'no-use-before-define': 'off'
  '@typescript-eslint/no-unused-vars':
    - 'error'
    - argsIgnorePattern: '^_'
  '@typescript-eslint/no-use-before-define':
    - error
    - functions: false
  # disable this temporarily since we have a lot of JS files
  # and typescript-eslint runs against JS files too
  '@typescript-eslint/explicit-module-boundary-types': off
  '@typescript-eslint/ban-ts-comment': 'off'
  '@typescript-eslint/ban-ts-ignore': 'off'
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps:
    - warn
    - additionalHooks: useRecoilCallback
  simple-import-sort/imports: error
#   quotes: ["error", "single"]
#   strict: ["error", "never"]
#   no-console: "warn"
